export const sampleCareers = [
    {
        id: "1",
        title: "Software Engineer",
        company: "Algorizz",
        description: "We are looking for a software engineer to join our team.",
        location: "Remote",
        startDate: "2022-01-01",
        createdAt: "2021-12-01T00:00:00Z",
    },
    {
        id: "2",
        title: "Data Scientist",
        company: "Algorizz",
        description: "We are looking for a data scientist to join our team.",
        location: "Remote",
        startDate: "2022-01-01",
        createdAt: "2021-12-01T00:00:00Z",
    },
    {
        id: "3",
        title: "Product Manager",
        company: "Algorizz",
        description: "We are looking for a product manager to join our team.",
        location: "Remote",
        startDate: "2022-01-01",
        createdAt: "2021-12-01T00:00:00Z",
    },
    {
        id: "4",
        title: "UX Designer",
        company: "Algorizz",
        description: "We are looking for a UX designer to join our team.",
        location: "Remote",
        startDate: "2022-01-01",
        createdAt: "2021-12-01T00:00:00Z",
    },
    {
        id: "5",
        title: "QA Engineer",
        company: "Algorizz",
        description: "We are looking for a QA engineer to join our team.",
        location: "Remote",
        startDate: "2022-01-01",
        createdAt: "2021-12-01T00:00:00Z",
    },
    {
        id: "6",
        title: "Technical Writer",
        company: "Algorizz",
        description: "We are looking for a technical writer to join our team.",
        location: "Remote",
        startDate: "2022-01-01",
        createdAt: "2021-12-01T00:00:00Z",
    }
];